cargo-features = ["edition2021"]

[package]
name = "compiler01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "*"
anyhow = "*"